### ISSUE TITLE
Support user console automatically login

### ISSUE THREAD

**Issue by simonschuang** [myelintek/web#148]
1. login component will create the user home directory while adduser without RSA key.

2. Try to look for the RSA key under home directory while user press button to launch the xterm. If the key not exists,  automatically generate the RSA key in the .ssh directory under home of the user. we should trust the user at this moment because users have been authenticated by the web login.

**Comment by vis-lee** [comment]
close the ticket   - automatically login from myelintek web portal.
please ref commit [bd2fb174c067133f953b14ed48a8a620348a8080](https://github.com/myelintek/myewebssh/commit/bd2fb174c067133f953b14ed48a8a620348a8080)
