### ISSUE TITLE
GPU utilization shift dramatically during training

### ISSUE THREAD

**Issue by simonschuang** [myelintek/web#20]
![1521451204472](https://user-images.githubusercontent.com/2860098/37587312-ee59a57c-2b99-11e8-9fe2-4cb707e369a3.gif)

**Comment by simonschuang** [comment]
Please use this command to see whether it's ssd or hdd
```
lsblk -d -o name,rota
```

**Comment by anastasiia-annata** [comment]
Output of 

> lsblk -d -o name,rota

NAME ROTA
sda     1
sdb     1
