### ISSUE TITLE
Was there a way to randomly partition the dataset into training dataset and validation dataset according to the input partition portions, e.g. 70% for training and 30% for validation?

### ISSUE THREAD

**Issue by eric-mcc** [myelintek/web#53]
Was there a way to randomly partition the dataset into training dataset and validation dataset according to the input partition portions, e.g. 70% for training and 30% for validation?
![image](https://user-images.githubusercontent.com/7124612/44065880-f25e4dec-9f9f-11e8-88a6-32e2e5d44c3a.png)

**Comment by simonschuang** [comment]
deprecated
