### ISSUE TITLE
Cant't perform Error Analysis on Model that trained by Bayesian(HPO) 

### ISSUE THREAD

**Issue by wewe0901** [myelintek/web#66]
From: 蕭羽廷 
Sent: Tuesday, October 2, 2018 7:25 AM
To: 李威儒 <WeiRu.Lee@itri.org.tw>
Cc: 莊尚益 <simonchuang@itri.org.tw>; 洪郁婷 <Connyhong@itri.org.tw>
Subject: RE: 《開通資訊》DNN Training System

威儒 您好，

前面的階段已經跑完，要跑model analysis，不過 “select model”選項是空的，點選他沒反應，請問我哪邊沒有操作好嗎?
謝謝您!

![baysian_training_cant_evaluate](https://user-images.githubusercontent.com/2045106/46325421-b86edf00-c62a-11e8-8303-ddd0c425a7eb.jpg)

**Comment by wewe0901** [comment]
User Model training are done
![user_model_done](https://user-images.githubusercontent.com/2045106/46325528-3df28f00-c62b-11e8-83d9-81a989264aa1.PNG)

User using Bayesian Optimization Mode
![user_model_usehpo](https://user-images.githubusercontent.com/2045106/46325543-54004f80-c62b-11e8-8769-7ad4bca8e279.PNG)

**Comment by simonschuang** [comment]
fixed
