### ISSUE TITLE
The training page not automatically refresh while running training jobs

### ISSUE THREAD

**Issue by simonschuang** [myelintek/web#9]
Normal page on Mac
<img width="992" alt="2018-03-12 11 23 33" src="https://user-images.githubusercontent.com/2860098/37264362-f145a784-25e7-11e8-84cb-cf57ff296b6b.png">

Not working on Ubuntu env
- Empty Dataset info. 
- Not automatically refreshing page
- line charts not display
<img width="884" alt="2018-03-12 11 23 44" src="https://user-images.githubusercontent.com/2860098/37264377-0200fe66-25e8-11e8-814b-4e5d99a9322f.png">

**Comment by wewe0901** [comment]
@simonschuang 
Its work on my Ubuntu 16.04.4 desktop version .
Could you provide the OS+distribution version and Browser version of you environment ?
![2018-03-07 11 51 53](https://user-images.githubusercontent.com/2045106/37315990-937c071e-2697-11e8-9b48-3cb02aca161a.png)

**Comment by simonschuang** [comment]
- Ubuntu 16.04.4(docker)
- Chrome 64.0.3282.186

**Comment by simonschuang** [comment]
Can't reproduce
